security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginCodeAuthenticator
            entry_point: App\Security\LoginEntryPoint
            logout:
                path: app_logout

    access_control:
        - { path: ^/(en/login(/verify)?|pt/entrar(/verificar)?)$, roles: PUBLIC_ACCESS }
        - { path: ^/(en/about|pt/sobre)$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
