security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            login_link:
                check_route: app_login_check
                signature_properties: ['email']
                lifetime: '%env(int:LOGIN_TOLERANCE_TIME)%'
                max_uses: 1
                used_link_cache: cache.app
                success_handler: App\Security\LoginSuccessHandler
                failure_handler: App\Security\LoginFailureHandler
            entry_point: App\Security\MagicLinkEntryPoint
            logout:
                path: app_logout

    access_control:
        - { path: ^/send-magic-link, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
