version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    working_dir: /var/www/html
    tty: true
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'